---
all:
  children:
    windows:
      hosts:
        windows_server_2025:
          ansible_host: "{{ lookup('env', 'WINDOWS_SERVER_IP') }}"
          ansible_user: adminuser
          ansible_password: "{{ lookup('env', 'WINDOWS_ADMIN_PASSWORD') }}"
          ansible_connection: winrm
          ansible_winrm_transport: ntlm
          ansible_winrm_server_cert_validation: ignore
          ansible_port: 5986
      vars:
        ansible_shell_type: powershell

    linux:
      children:
        rhel:
          hosts:
            rhel_server:
              ansible_host: "{{ lookup('env', 'RHEL_SERVER_IP') }}"
              ansible_user: adminuser
              ansible_ssh_private_key_file: "{{ lookup('env', 'RHEL_SSH_KEY_PATH') }}"
              ansible_become: true
              ansible_become_method: sudo
        
  vars:
    environment: dev
    project_name: ejbca-platform
    azure_keyvault_name: "{{ lookup('env', 'AZURE_KEYVAULT_NAME') }}"

