apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ejbca-ce.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ejbca-ce.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

