apiVersion: v1
kind: Service
metadata:
  name: {{ include "ejbca-ce.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ejbca-ce.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.http.port }}
      targetPort: {{ .Values.service.ports.http.targetPort }}
      protocol: {{ .Values.service.ports.http.protocol }}
      name: http
    - port: {{ .Values.service.ports.https.port }}
      targetPort: {{ .Values.service.ports.https.targetPort }}
      protocol: {{ .Values.service.ports.https.protocol }}
      name: https
    - port: {{ .Values.service.ports.admin.port }}
      targetPort: {{ .Values.service.ports.admin.targetPort }}
      protocol: {{ .Values.service.ports.admin.protocol }}
      name: admin
  selector:
    {{- include "ejbca-ce.selectorLabels" . | nindent 4 }}

