apiVersion: v1
kind: Namespace
metadata:
  name: artifactory
  labels:
    name: artifactory
    linkerd.io/inject: enabled
  annotations:
    description: "JFrog Artifactory universal artifact repository"

